### ISSUE TITLE
different change feed systems a problem?

### ISSUE THREAD

**Issue by michielbdejong** [Decentralized-Sharing-Working-Group/internet-draft#2]
@Gara64 I don't know what to do with [this sentence](https://github.com/Decentralized-Sharing-Working-Group/internet-draft/blob/9c60938fe35b9e73bd2a75b4faa15bf4d7ed24d1/source.txt#L436-L437)

As long as the servers understand each other's proposed changes, they don't have to run the same software, right?

A server may even support more than one change feed method?

**Comment by paultranvan** [comment]
Yes I implied the change feed algorithm should be the same between A and B, no matter what is the software running behind. 
A server could support more than one change feed method, as long as it possible to determine which one to use. It's better to guarantee interoperability with many, but probably complicated to implement :)
Different methods also breaks the sync transitivity (if A is synchronized with B and C, using 2 differents method, B cannot  be synchronized with C), but we focus on a 1-to-1 sharing, so it's not relevant here.

**Comment by michielbdejong** [comment]
The way I described it now, it's hub-and-spoke, with Alice's version in the center. What do you call a change feed algorithm? I think the constraints for change feeds are:
- they are append-only lists of either incremental changeset objects or entire new versions.
- if incremental changesets, then they should start from the previous version, and the patch algorithm should be indicated (for instance [unix patch](https://en.wikipedia.org/wiki/Patch_%28Unix%29)).
- if a changeset has been copied from some other feed (for instance Alice merging a change proposed by Bob), then it should link to that, either by its URL, or by its hash in some hashing algorithm.

**Comment by paultranvan** [comment]
By algorithm I meant the versioning. If Alice and Bob cannot agree on the same versionning system, how could they know that some changes occured and detect the conflicts?

**Comment by michielbdejong** [comment]
Let's discuss on irc!
