### ISSUE TITLE
Improve example about incompatible vocabularies

### ISSUE THREAD

**Issue by michielbdejong** [Decentralized-Sharing-Working-Group/internet-draft#5]
I couldn't really find the right words about what happens when Alice uses Turtle+DBPedia and Bob uses Turtle+MicroFormats, I'll try to look for a more convincing or more specific example of why agreeing on data syntax does not apply agreeing on data semantics, even when following same-as links between vocabularies.

**Comment by paultranvan** [comment]
If you don't feel confortable enough on this, you can skip this [part](https://github.com/Decentralized-Sharing-Working-Group/internet-draft/blob/master/source.txt#L616-L652) to just keep the last paragraph, which is basically saying "let's follow the recommandations of the [SocialWG](http://www.w3.org/Social/WG)" 
It's up to you :)

**Comment by michielbdejong** [comment]
Leaving it out of scope may be a good option, yes.

**Comment by michielbdejong** [comment]
I reread it, changed a few wordings, and it seems fine to me now.
