### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by paultranvan** [Decentralized-Sharing-Working-Group/internet-draft#7]
There is not a clear paragraph about the motivations of the document, eg defining and structure what is a decentralized sharing, what are the challenges, in order to provide some kind of guideline to those who want to implement this sharing and be interoperable with others.
Should we add a motivation or is it irrelevant for the IETF format?

**Comment by michielbdejong** [comment]
I think it's quite clear from https://github.com/Decentralized-Sharing-Working-Group/internet-draft/blob/master/source.txt#L12 and https://github.com/Decentralized-Sharing-Working-Group/internet-draft/blob/master/source.txt#L158? Some of our motivations are also implied by the fact that we're publishing an I-D I think, yes. Those two remarks try to explain that we're just describing the problem and hinting at existing possible solutions. The 'want to be interoperable' is I think explained by https://github.com/Decentralized-Sharing-Working-Group/internet-draft/blob/master/source.txt#L141-L156, but feel free to improve!

**Comment by paultranvan** [comment]
Just added a phrase to make it more explicit : #8

**Comment by michielbdejong** [comment]
Merged!
